% Dialog box to manually move the figure over the extended area of the video projector where the Fourier patterns will be displayed. 
% Allows you to make the settings manually and to start the acquisitions afterwards by pressing a 'Next' button.
function DialogBox
    d = dialog('Position',[300 300 250 150],'Name','DialogBox');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'Position',[20 80 210 40],...
               'String','Arrange the figure on the extended area of the projector and press Next to begin acquisition.');
    figure(1)
    btn = uicontrol('Parent',d,...
               'Position',[85 20 70 25],...
               'String','Next',...
               'Callback','delete(gcf)');
    
    uiwait(d);
end